### ISSUE TITLE
Abandon BIC and AIC, discuss

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#22]
Hi All,

I have a proposal for PF2. Right now we calculate three metrics: 

AIC, AICc, BIC

My proposal is that we ditch them all apart from the AICc. Here's why.

First, there is no reason to ever use the AIC over the AICc. The AICc corrects for small sample sizes, and converges to the AIC for larger sample sizes (see Burnham and Anderson's book). So providing both is pointless and perhaps even misleading.

Second, the BIC is not really an information criterion at all (it's only named as such). And more importantly, it makes some totally untenable assumptions for molecular phylogenetics. Most egregiously, it assumes that the TRUE model is in the set being considered. This is ridiculously far from the truth for phylogenetics. Perhaps because of this, the only studies that really show support for the accuracy of the BIC are simulation studies, where that one ridiculous rule is actually true - in the simulation studies that showed support for the BIC the true model IS in the set being considered.

Reducing everything to a single metric makes the program simpler, and would help to move the field along a bit too.

Any thoughts?

Rob

**Comment by cmayer** [comment]
Hi Rob,

I am not sure PF should stop to support the AIC and the BIC.

Even if there is no good scientific reason to use the AIC rather than the AICc, people
might have used it in the past. If you drop the AIC you also lose "backwards compatibility" of results
and comparability.

Concerning the BIC I am not sure it should be dropped that for the same reason.
If the true model is not among the models we test for, the user will have a problem anyway - at least from
the perspective of maximum likelihood consistency.

The theoretical objective of the AIC (or AICc) is to find the model with the least information loss with respect to the true model.
The fact that the BIC outperforms the AIC if the true model is among the models we test for is of course interesting from this point
of view.

I always used the AICc since it convinced me more than the others, but people might think different.
If I would not use the AICc I would almost certainly be unhappy about loosing the AIC or BIC, since I still sometimes
compare partitioning results of newer versions/algorithms with older results.

Best
Christoph


 

Am 18.01.2015 um 03:27 schrieb roblanf:

> Hi All,
> 
> I have a proposal for PF2. Right now we calculate three metrics:
> 
> AIC, AICc, BIC
> 
> My proposal is that we ditch them all apart from the AICc. Here's why.
> 
> First, there is no reason to ever use the AIC over the AICc. The AICc corrects for small sample sizes, and converges to the AIC for larger sample sizes (see Burnham and Anderson's book). So providing both is pointless and perhaps even misleading.
> 
> Second, the BIC is not really an information criterion at all (it's only named as such). And more importantly, it makes some totally untenable assumptions for molecular phylogenetics. Most egregiously, it assumes that the TRUE model is in the set being considered. This is ridiculously far from the truth for phylogenetics. Perhaps because of this, the only studies that really show support for the accuracy of the BIC are simulation studies, where that one ridiculous rule is actually true - in the simulation studies that showed support for the BIC the true model IS in the set being considered.
> 
> Reducing everything to a single metric makes the program simpler, and would help to move the field along a bit too.
> 
> Any thoughts?
> 
> Rob
> 
> —
> Reply to this email directly or view it on GitHub.
> 

****************************************
Dr. Christoph Mayer
Email:  c.mayer.zfmk@uni-bonn.de
Tel.:   +49 (0)228 9122 403

Zoologisches Forschungsmuseum Alexander Koenig
- Leibniz Institut für Biodiversität der Tiere -
Adenauerallee 160
53113 Bonn, Germany 
www.zfmk.de

Stiftung des öffentlichen Rechts; Direktor: Prof. J. W. Wägele
Sitz: Bonn
****************************************

**Comment by wrightaprilm** [comment]
I agree with Christoph. I'm using PF for morphology, and my investigations show that AIC oversplits pretty strongly in small datasets (will send a paper draft to you next week so you can see, too), and BIC fairly mildly. I think the thing to do is to make AICc the default, and to retool the manual and log messages to discourage the use of AIC and BIC.

**Comment by roblanf** [comment]
I agree in one sense.

But in another sense I want to challenge you to explain why the BIC is
better, and how you know the AIC (or AICc) is oversplitting? My point is
that our models are so so wrong that if you think the AIC is oversplitting,
it probably means we should be working on other aspects of the models
and/or model selection, rather than using a deeply inappropriate metric to
hide the issue.

I guess I feel like someone has to make the call here, and I'm very tempted
to make it in PF2.

R

On 5 February 2015 at 07:47, April Wright <notifications@github.com> wrote:

> I agree with Christoph. I'm using PF for morphology, and my investigations
> show that AIC oversplits pretty strongly in small datasets (will send a
> paper draft to you next week so you can see, too), and BIC fairly mildly. I
> think the thing to do is to make AICc the default, and to retool the manual
> and log messages to discourage the use of AIC and BIC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/22#issuecomment-72913659>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by wrightaprilm** [comment]
Oversplitting is a slippery concept. I would say oversplitting is contextual: you've oversplit your data when you can no longer estimate a tree from those data. With AIC, I run into convergence difficulties with most of the datasets in otherwise equivalent methods for phylogenetic esitmation (ie, only the partition scheme is changing). Datasets partitioned with AICc and BIC have no such problems. I'm attaching a figure here. AIC has an incredibly long tail, in which it supports little partitions of 1-2 characters. Regardless of the underlying model, actually doing the fitting is going to be very hard in that space.
![fig2](https://cloud.githubusercontent.com/assets/1715446/6047295/63cd032a-ac6e-11e4-997f-c28e7efca070.png)

**Comment by cmayer** [comment]
Hi Rob,

Am 04.02.2015 um 19:56 schrieb roblanf:

> I agree in one sense.
> 
> But in another sense I want to challenge you to explain why the BIC is
> better, and how you know the AIC (or AICc) is oversplitting? My point is
> that our models are so so wrong that if you think the AIC is oversplitting,
> it probably means we should be working on other aspects of the models
> and/or model selection, rather than using a deeply inappropriate metric to
> hide the issue.
> 
> I guess I feel like someone has to make the call here, and I'm very tempted
> to make it in PF2.

I see the point, but people do not like to be forced to change their methods.
For the reason of backward compatibility and since some people prefer it
I would still offer the AIC and BIC.
I know how much people talk about Alexi, since he wants people to use
model+G and not model+I+G. Researchers want to have the freedom of choice,
and maybe they just want to be able to compare the methods.
Convincing people "by force" is usually neither appreciated nor successful.

I do share your opinion that the AICc is better justified than the AIC or BIC.
I just think that limiting the features of a software is not the right answer to this
question.

All the best
Christoph


> 
> R
> 
> On 5 February 2015 at 07:47, April Wright <notifications@github.com> wrote:
> 
> > I agree with Christoph. I'm using PF for morphology, and my investigations
> > show that AIC oversplits pretty strongly in small datasets (will send a
> > paper draft to you next week so you can see, too), and BIC fairly mildly. I
> > think the thing to do is to make AICc the default, and to retool the manual
> > and log messages to discourage the use of AIC and BIC.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/brettc/partitionfinder/issues/22#issuecomment-72913659>
> > .
> >
> 
> 
> 
> -- 
> Rob Lanfear
> School of Biological Sciences,
> Macquarie University,
> Sydney
> 
> phone: +61 (0)2 9850 8204
> 
> www.robertlanfear.com
> —
> Reply to this email directly or view it on GitHub.
> 

****************************************
Dr. Christoph Mayer
Email:  c.mayer.zfmk@uni-bonn.de
Tel.:   +49 (0)228 9122 403

Zoologisches Forschungsmuseum Alexander Koenig
- Leibniz Institut für Biodiversität der Tiere -
Adenauerallee 160
53113 Bonn, Germany 
www.zfmk.de

Stiftung des öffentlichen Rechts; Direktor: Prof. J. W. Wägele
Sitz: Bonn
****************************************

**Comment by roblanf** [comment]
Christoph - I see your point, and to some extent I feel like I'll do
anything for a quiet life.

April - now I see. I was proposing to only have AICc. In fact, there is
really never any reason to use AIC over AICc, so it's refreshing that AICc
gives you sensible answers.



On 5 February 2015 at 11:24, cmayer <notifications@github.com> wrote:

> Hi Rob,
>
> Am 04.02.2015 um 19:56 schrieb roblanf:
>
> > I agree in one sense.
> >
> > But in another sense I want to challenge you to explain why the BIC is
> > better, and how you know the AIC (or AICc) is oversplitting? My point is
> > that our models are so so wrong that if you think the AIC is
> oversplitting,
> > it probably means we should be working on other aspects of the models
> > and/or model selection, rather than using a deeply inappropriate metric
> to
> > hide the issue.
> >
> > I guess I feel like someone has to make the call here, and I'm very
> tempted
> > to make it in PF2.
>
> I see the point, but people do not like to be forced to change their
> methods.
> For the reason of backward compatibility and since some people prefer it
> I would still offer the AIC and BIC.
> I know how much people talk about Alexi, since he wants people to use
> model+G and not model+I+G. Researchers want to have the freedom of choice,
> and maybe they just want to be able to compare the methods.
> Convincing people "by force" is usually neither appreciated nor successful.
>
> I do share your opinion that the AICc is better justified than the AIC or
> BIC.
> I just think that limiting the features of a software is not the right
> answer to this
> question.
>
> All the best
> Christoph
>
>
> >
> > R
> >
> > On 5 February 2015 at 07:47, April Wright <notifications@github.com>
> wrote:
> >
> > > I agree with Christoph. I'm using PF for morphology, and my
> investigations
> > > show that AIC oversplits pretty strongly in small datasets (will send a
> > > paper draft to you next week so you can see, too), and BIC fairly
> mildly. I
> > > think the thing to do is to make AICc the default, and to retool the
> manual
> > > and log messages to discourage the use of AIC and BIC.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/brettc/partitionfinder/issues/22#issuecomment-72913659>
> > > .
> > >
> >
> >
> >
> > --
> > Rob Lanfear
> > School of Biological Sciences,
> > Macquarie University,
> > Sydney
> >
> > phone: +61 (0)2 9850 8204
> >
> > www.robertlanfear.com
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> ****************************************
> Dr. Christoph Mayer
> Email: c.mayer.zfmk@uni-bonn.de
> Tel.: +49 (0)228 9122 403
>
> Zoologisches Forschungsmuseum Alexander Koenig
> - Leibniz Institut für Biodiversität der Tiere -
> Adenauerallee 160
> 53113 Bonn, Germany
> www.zfmk.de
>
> Stiftung des öffentlichen Rechts; Direktor: Prof. J. W. Wägele
> Sitz: Bonn
> ****************************************
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/22#issuecomment-72953188>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by wrightaprilm** [comment]
Right. I still don't think that aking away AIC and BIC are the way to go. As part of my paper, I reproduce previous work and evaluate the same partitions used in another paper using AIC and BIC, which is what they used, then procede to search for another scheme using AICc (after demonstrating AICc is better-behaved).  Uses like that are still valueable. I vote for leaving it in, but making it clear that AICc is the better-justified criterion.

**Comment by wookietreiber** [comment]
To weigh in here, @wrightaprilm logic is on your side: still providing both AIC and BIC for backwards compatibility / reproducing results / producing comparable results is most certainly a valid argument, while making AICc the default seems to be very reasonable.

**Comment by wrightaprilm** [comment]
Oh, absolutely. I just wanted to make the point that this isn't a hypthetical future use someone might do, it's something I have done and likely will do again in the future.

**Comment by roblanf** [comment]
OK. Got it. I am convinced.

Thanks!

R

On 7 February 2015 at 05:25, April Wright <notifications@github.com> wrote:

> Oh, absolutely. I just wanted to make the point that this isn't a
> hypthetical future use someone might do, it's something I have done and
> likely will do again in the future.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/22#issuecomment-73263960>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by roblanf** [comment]
done.
